# Netlify Build-Anweisungen
[build]
  # Directory where the build output is located (if applicable)
  publish = "dist" # Adjust this if your frontend build output is in a different folder
  # Directory for Netlify functions
  functions = "netlify/functions"

[functions]
  # Include additional files or folders required by functions
  included_files = ["netlify/functions/data/**"]

# Header für die Funktion (CORS & Content-Type)
[[headers]]
  for = "/.netlify/functions/getcsvdata"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Erlaubt alle Domains (für Tests)
    Content-Type = "application/json"  # Sagt dem Browser, es ist JSON-Daten

# Redirects für eine schönere URL (optional)
[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/getcsvdata"
  status = 200
